name: "Compute Docker Tag"
description: "Compute Docker image tag for this GitHub push/pull_request/tag"
inputs:
  fixme-fixme-fixme:
    description: "Fixme fixme"
    required: false
    default: "fixme"
outputs:
  tag:
    description: "The Docker image tag for this GitHub push/pull_request/tag"
runs:
  using: "node16"
  main: "index.js"
