name: Some dependent action build this project

on:
  workflow_call:

jobs:
  build_smth:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/compute-docker-tag
        id: compute-docker-tag
