name: Build, then test, then publish

on:
  push:
    branches:
      - "*"
    tags:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    uses: ./.github/workflows/build-smth.yml
  test:
    uses: ./.github/workflows/test-smth.yml
    needs: build
  publish:
    uses: ./.github/workflows/publish-smth.yml
    needs: test
